name: deploy azure policy and initiative

on:
  push:
    paths:
      - 'Keyvaultinitiative/**'
  workflow_dispatch:

jobs:
  deploy-policy:
    runs-on: windows-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: login to azure with azure login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: deploy policy and initiative with pwsh script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: ./azure-scripts/deploy-policy.ps1